<?php
    /** @var Magento\Framework\View\Element\Template $block; */
?>
<html>
    <body style="background: font-family: "Helvetica Neue", Helvetica, Arial, sans-serif">
        <div style="padding-left: 1.5rem; padding-top: 3rem;">
            <p>Vendor: <?=$block->getRequest()->getParam('vendor')?>
            <p>Module: <?=$block->getRequest()->getParam('module')?>
        </div>
    </body>
</html>
