<?php
    /** @var Magento\Framework\View\Element\Template $block; */
?>
<html>
    <body style="background: radial-gradient(circle, rgba(238,174,202,1) 0%, rgba(148,187,233,1) 100%); font-family: "Helvetica Neue", Helvetica, Arial, sans-serif">
        <div style="padding-left: 1.5rem; padding-top: 3rem;">
            <p>Vendor: <?=$block->getRequest()->getParam('vendor')?>
            <p>Module: <?=$block->getRequest()->getParam('module')?>
        </div>
    </body>
</html>
