<?php
/**
 * @var \Nadiiaz\RegularCustomer\Block\Product\View\DiscountRequest $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
/** @var \Magento\Catalog\Model\Product $product */
$product = $block->getData('product');
$isModal = 'false';

if ($block->getData('is_modal')) {
    $isModal = 'true';
}
?>
<div class="nadiiaz-personal-discount-request">
    <form class="form nadiiaz-personal-discount-form"
          action="/errors/404.php"
          onsubmit="return false;"
          method="post"
          data-mage-init='{"Nadiiaz_RegularCustomer_form":{
              "action": "<?= $escaper->escapeHtmlAttr($block->getData('request_submit_url')) ?>",
              "isModal": <?= $escaper->escapeHtmlAttr($isModal) ?>
          }}'
    >
        <fieldset class="fieldset">
            <?php if ($isModal === 'false'): ?>
            <legend class="legend">
                <span><?= $escaper->escapeHtml(__('Loyalty program for Regular Customers')) ?></span>
            </legend>
            <br/>
            <div>
                <span><?= $escaper->escapeHtml(__('Customers who buy products multiple times get a discount when buying multiple items. Only registered customers will get discounts')) ?></span>
            </div>
            <br/>
            <?php endif; ?>
            <?php // @TODO: Get current customer name and email for logged in customers ?>
            <div class="field name required">
                <label class="label" for="name">
                    <span><?= $escaper->escapeHtml(__('Name')) ?></span>
                </label>
                <div class="control">
                    <input name="name"
                           title="<?= $escaper->escapeHtmlAttr(__('Name')) ?>"
                           class="input-text"
                           type="text"
                           data-validate="{required:true}"
                    />
                </div>
            </div>
            <div class="field email required">
                <label class="label" for="email">
                    <span><?= $escaper->escapeHtml(__('Email')) ?></span>
                </label>
                <div class="control">
                    <input name="email"
                           title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                           class="input-text"
                           type="email"
                           data-validate="{required:true, 'validate-email':true}"
                    />
                </div>
            </div>
        </fieldset>
        <?php if ($product): ?>
        <div class="actions-toolbar">
            <input type="hidden"
                   name="product_id"
                   value="<?= $escaper->escapeHtmlAttr((int) $product->getId()) ?>"
            />
        <?php endif; ?>
            <div class="primary">
                <button type="submit"
                        title="<?= $escaper->escapeHtmlAttr(__('Send Request')) ?>"
                        class="action submit primary"
                >
                    <span><?= $escaper->escapeHtml(__('Send Request')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
