<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
/** @var \Magento\Catalog\Model\Product $product */
$product = $block->getData('product');
?>
<button class="action primary" data-mage-init='{"Nadiiaz_RegularCustomer_formOpenButton":{}}'">
    <span><?= $escaper->escapeHtml(__('Request Personal Discount'))?></span>
</button>
