<div class="nadiiaz-personal-discount-request" data-bind="scope:'personalDiscountRequestForm'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
{
   "*": {
       "Magento_Ui/js/core/app": {
          "components": {
               "personalDiscountRequestForm": {
                   "component": "Nadiiaz_RegularCustomer_form",
                        "action": "<?= $escaper->escapeJs($block->getUrl('nadiiaz_personal_discount/index/request')) ?>",
                        "productId": <?= (int) $block->getProduct()->getId() ?>,
                        "isModal": <?= $escaper->escapeJs($isModal) ?>
               }
           }
       }
   }
}
</script>


