<?php
/**
 * @var \Nadiiaz\RegularCustomer\Block\Product\View\DiscountRequest $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
/** @var \Magento\Catalog\Model\Product $product */
?>
<a href="<?= $escaper->escapeHtmlAttr($block->getUrl('regular_customer/request/form')) ?>" style="color: #0a6767">
        <?= $escaper->escapeHtml(__('Loyalty program')) ?></a>
